In [15]:
import numpy as np
import math
import cmath
from math import  sqrt
import qiskit
from qiskit.visualization import array_to_latex
X = np.array([[0, 1], [1, 0]])
Z = np.array([[1, 0], [0, -1]])
H1 = np.array([[1/sqrt(2), 1/sqrt(2)], [1/sqrt(2), -1/sqrt(2)]])
H = np.array([[2, 3], [4, 5]])
Y = np.array([[0, -1j],
              [1j, 0]])
I = np.array([[1, 0], [0, 1]])
CNOT = np.array([[1, 0, 0, 0],
                 [0, 1, 0, 0],
                 [0, 0, 0, 1],
                 [0, 0, 1, 0]])
CNOT3=np.array([[1, 0, 0, 0,0,0,0,0],
                 [0, 1, 0, 0,0,0,0,0],
                 [0, 0, 1, 0,0,0,0,0],
                 [0, 0, 0, 1,0,0,0,0],
                 [0, 0, 0, 0,0,1,0,0],
                 [0, 0, 0, 0,1,0,0,0],
                 [0, 0, 0, 0,0,0,0,1],
                 [0, 0, 0, 0,0,0,1,0]])
SWAP = np.array([[1, 0, 0, 0],
                 [0, 0, 1, 0],
                 [0, 1, 0, 0],
                 [0, 0, 0, 1]])
T=np.array([[1, 0], [0, math.e**(math.pi/4)]])
F=np.array([[1, 0],
                     [0, np.exp(1j * np.pi/2)]])
B=np.kron(I,H)
array_to_latex(B, prefix='XX=')
V1 = np.array([[2,3,4,5,6,7,8,9]])
V2 = np.array([[2,6,4,8,3,7,5,9]])
#V1 = np.random.rand(16)

In [16]:

#print(tensor_product(I,I,H1))
print(matrix_product(tensor_product(I,I,H1),V1.T))
print(matrix_product(tensor_product(H1,I,I),V2.T))

[[ 3.53553391]
 [-0.70710678]
 [ 6.36396103]
 [-0.70710678]
 [ 9.19238816]
 [-0.70710678]
 [12.02081528]
 [-0.70710678]]
[[ 3.53553391]
 [ 9.19238816]
 [ 6.36396103]
 [12.02081528]
 [-0.70710678]
 [-0.70710678]
 [-0.70710678]
 [-0.70710678]]


In [5]:
def tensor_product(*tensors):
    """
    Compute the tensor product of multiple tensors.
    
    Parameters:
        *tensors (list of np.ndarray): List of tensors to compute the tensor product.
    
    Returns:
        np.ndarray: Resulting tensor after tensor product.
    """
    result = tensors[0]
    for tensor in tensors[1:]:
        result = np.kron(result, tensor)
    return result

In [4]:
def matrix_product(*matrices):
    """
    Compute the product of multiple matrices.
    
    Parameters:
        *matrices (list of np.ndarray): List of matrices to compute the product.
    
    Returns:
        np.ndarray: Resulting matrix after multiplication.
    """
    # Verificar que hay al menos una matriz
    if len(matrices) == 0:
        raise ValueError("Se debe proporcionar al menos una matriz")
    
    # Inicializar el resultado con la primera matriz
    result = matrices[0]
    
    # Multiplicar secuencialmente las matrices
    for matrix in matrices[1:]:
        result = np.matmul(result, matrix)
    
    return result

In [39]:
res=np.dot(np.dot(resultado1,resultado2),resultado3)
for i in range(0,2**4):
    print(res[i])

[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]


In [3]:
resultado = tensor_product(CNOT,I)


#print(resultado)
for i in range(0,2**4):
    print(resultado[i])
#print(resultado.dot(V.T))
array_to_latex(resultado, prefix='IIM=')

[1 0 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0]
[0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 1]
[0 0 0 0 1 0 0 0]
[0 0 0 0 0 1 0 0]


IndexError: index 8 is out of bounds for axis 0 with size 8

In [3]:
n=2**30
from time import time
import numpy as np
inicio = time()
m=int(n/2)
V = np.random.rand(n)

#np.savetxt("datos.txt", V, delimiter=",")
#memoria = V.nbytes

#print("El array ocupa {} bytes de memoria.".format(memoria))
#print(V)
#print(resultado.dot(V.T))
fin = time()
print("Tiempo transcurrido:", "{:.10f}".format(fin-inicio))

inicio = time()
V3=np.zeros((n))

V2 = np.zeros((n, 4))
H = np.array([[2, 3], [4, 5]])
K=n/2**1
for i in range(0,m):
        V2[i]=[i,n/2+i,H[0][0],H[0][1]]
for i in range(0,m):
    V2[i+m]=[i,n/2+i,H[1][0],H[1][1]]


for i in range(0,n):
    V3[i] = V[int(V2[i][0])] * V2[i][2] + V[int(V2[i][1])] * V2[i][3]
fin = time()
print("Tiempo transcurrido:", "{:.10f}".format(fin-inicio))
#print(V3)


Tiempo transcurrido: 86.2362077236


'\ninicio = time()\nV3=np.zeros((n))\n\nV2 = np.zeros((n, 4))\nH = np.array([[2, 3], [4, 5]])\nK=n/2**1\nfor i in range(0,m):\n        V2[i]=[i,n/2+i,H[0][0],H[0][1]]\nfor i in range(0,m):\n    V2[i+m]=[i,n/2+i,H[1][0],H[1][1]]\n\n\nfor i in range(0,n):\n    V3[i] = V[int(V2[i][0])] * V2[i][2] + V[int(V2[i][1])] * V2[i][3]\nfin = time()\nprint("Tiempo transcurrido:", "{:.10f}".format(fin-inicio))\n#print(V3)\n'

In [5]:
import h5py
import numpy as np

# Crear un array de ejemplo
data = np.random.rand(2**30)

# Crear y abrir un archivo HDF5
with h5py.File('data2.h5', 'w') as f:
    # Crear un dataset y escribir datos en él
    f.create_dataset('dataset_name', data=data)

print("Datos guardados en data.h5")

/mnt/c/Users/sergio.muniz/Desktop/VQE/.venv/lib/python3.10/site-packages/numpy/core/getlimits.py:542: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\x00\x00\x00\x00\x00\x00' for <class 'numpy.longdouble'> does not match any known type: falling back to type probe function.
This warnings indicates broken support for the dtype!
  machar = _get_machar(dtype)


Datos guardados en data.h5


In [1]:
import h5py
import numpy as np
with h5py.File('data.h5', 'r') as f:
    # Acceder al dataset
    dataset = f['dataset_name']
    
    # Leer los datos del dataset
    data = np.array(dataset)

# Imprimir algunos datos para verificar
print("Datos leídos del archivo HDF5:")
print(data)

/mnt/c/Users/sergio.muniz/Desktop/VQE/.venv/lib/python3.10/site-packages/numpy/core/getlimits.py:542: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\x00\x00\x00\x00\x00\x00' for <class 'numpy.longdouble'> does not match any known type: falling back to type probe function.
This warnings indicates broken support for the dtype!
  machar = _get_machar(dtype)


Datos leídos del archivo HDF5:
[0.51588309 0.73402182 0.96068939 ... 0.09398869 0.1868338  0.80659484]


In [2]:
import numpy as np

# Definir los 30 vectores con dos coeficientes cada uno
vectors = [np.array([1, 0]), np.array([1, 0]), np.array([1, 0]), np.array([1, 0]),
           np.array([1, 0]), np.array([1, 0]), np.array([1, 0]), np.array([1, 0]),
           np.array([1, 0]), np.array([1, 0]), np.array([1, 0]), np.array([1, 0]),
           np.array([1, 0]), np.array([1, 0]), np.array([1, 0]), np.array([1, 0]),
           np.array([1, 0]), np.array([1, 0]), np.array([1, 0]), np.array([1, 0]),
           np.array([1, 0]), np.array([1, 0]), np.array([1, 0]), np.array([1, 0]),
           np.array([1, 0]), np.array([1, 0]), np.array([1, 0]), np.array([1, 0]),
           np.array([1, 0]), np.array([1, 0]),np.array([1, 0]), np.array([1, 0])]

# Función para realizar el producto tensorial de una lista de vectores
def tensor_product(vectors):
    result = vectors[0]
    for vec in vectors[1:]:
        result = np.kron(result, vec)
    return result

# Calcular el producto tensorial
tensor_result = tensor_product(vectors)

# Imprimir la forma del resultado para verificar
print("Forma del resultado tensorial:", tensor_result.shape)

# Imprimir el resultado tensorial
print("Resultado tensorial:")
print(tensor_result)

Forma del resultado tensorial: (4294967296,)
Resultado tensorial:
[1 0 0 ... 0 0 0]


In [1]:
import h5py
import numpy as np

V2 = np.random.rand(2**29)
V1 = np.random.rand(2**29)
V=2*V1+7*V1

with h5py.File('data3.h5', 'w') as f:
    # Crear un dataset y escribir datos en él
    f.create_dataset('dataset_name', data=V)

/mnt/c/Users/sergio.muniz/Desktop/VQE/.venv/lib/python3.10/site-packages/numpy/core/getlimits.py:542: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\x00\x00\x00\x00\x00\x00' for <class 'numpy.longdouble'> does not match any known type: falling back to type probe function.
This warnings indicates broken support for the dtype!
  machar = _get_machar(dtype)


In [4]:
import numpy as np

V=2*V1+7*V2

In [12]:
import h5py
import numpy as np

n = 2**30

# Crear un array de ceros de tamaño 2**30
V = np.zeros(n)
# Establecer el primer coeficiente a 1
V[0] = 1
with h5py.File('data.h5', 'w') as f:
    # Crear un dataset y escribir datos en él
    f.create_dataset('dataset_name', data=V)

In [13]:
with h5py.File('data.h5', 'r') as f:
    # Acceder al dataset
    dataset = f['dataset_name']
    
    # Leer los datos del dataset
    V = np.array(dataset)

In [14]:
# 10 qubits and tag the initial wavefunction tensors
circ = qtn.Circuit(N=10)

# initial layer of hadamards
for i in range(10):
    circ.apply_gate('H', i, gate_round=0)

# 8 rounds of entangling gates
for r in range(1, 9):

    # even pairs
    for i in range(0, 10, 2):
        circ.apply_gate('CX', i, i + 1, gate_round=r)

    # Y-rotations
    for i in range(10):
        circ.apply_gate('RZ', 1.234, i, gate_round=r)

    # odd pairs
    for i in range(1, 9, 2):
        circ.apply_gate('CZ', i, i + 1, gate_round=r)

    # X-rotations
    for i in range(10):
        circ.apply_gate('RX', 1.234, i, gate_round=r)

# final layer of hadamards
for i in range(10):
    circ.apply_gate('H', i, gate_round=r + 1)

circ

<Circuit(n=10, num_gates=252, gate_opts={'contract': 'auto-split-gate', 'propagate_tags': 'register'})>