In [2]:
import numpy as np
import warnings
import matplotlib.pyplot as plt
# Suprime todas las advertencias
warnings.filterwarnings("ignore")
from qiskit import QuantumCircuit, transpile
from qiskit.qasm2 import dumps
from qiskit.qasm2 import dump

def add_random_rotation_gate(circuit, qubits):
    gate = np.random.choice(['rx', 'ry', 'rz'])
    qubit = np.random.randint(qubits)
    angle = np.random.uniform(0, 2 * np.pi)
    
    if gate == 'rx':
        circuit.rx(angle, qubit)
    elif gate == 'ry':
        circuit.ry(angle, qubit)
    elif gate == 'rz':
        circuit.rz(angle, qubit)

def add_random_cnot_gate(circuit, qubits):
    ctrl, target = np.random.choice(qubits, 2, replace=False)
    circuit.cx(ctrl, target)

# Crear un circuito cuántico con 30 qubits

n_qubits = 20
n_gates = 5
circ = QuantumCircuit(n_qubits, n_qubits)

# Aplicación de las puertas
for _ in range(n_gates):
    add_random_rotation_gate(circ, n_qubits)

for _ in range(n_gates):
    add_random_cnot_gate(circ, n_qubits)

for _ in range(n_gates):
    add_random_rotation_gate(circ, n_qubits)

for _ in range(n_gates):
    add_random_cnot_gate(circ, n_qubits)

for _ in range(n_gates):
    add_random_rotation_gate(circ, n_qubits)

for _ in range(n_gates):
    add_random_cnot_gate(circ, n_qubits)

for _ in range(n_gates):
    add_random_rotation_gate(circ, n_qubits)

for _ in range(n_gates):
    add_random_cnot_gate(circ, n_qubits)

for _ in range(n_gates):
    add_random_rotation_gate(circ, n_qubits)

for _ in range(n_gates):
    add_random_cnot_gate(circ, n_qubits)

with open("circuit_random.qasm", "w") as f:
    dump(circ, f)

In [82]:
import numpy as np
import warnings
import matplotlib.pyplot as plt
# Suprime todas las advertencias
warnings.filterwarnings("ignore")
from qiskit import QuantumCircuit, transpile
from qiskit.qasm2 import dumps
from qiskit.qasm2 import dump

n_qubits = 3
n_gates = 3
circ = QuantumCircuit(n_qubits, n_qubits)
circ.h(1)
#circ.cx(0,1)
print(circ)

with open("circuit.qasm", "w") as f:
    dump(circ, f)

          
q_0: ─────
     ┌───┐
q_1: ┤ H ├
     └───┘
q_2: ─────
          
c: 3/═════
          


In [96]:
import numpy as np
import warnings
import matplotlib.pyplot as plt
# Suprime todas las advertencias
warnings.filterwarnings("ignore")
from qiskit import QuantumCircuit, transpile
from qiskit_aer import AerSimulator
from qiskit.quantum_info import Statevector, random_statevector
from qiskit.qasm2 import dump
from qiskit.qasm2 import loads
simulator = AerSimulator(method='matrix_product_state')

with open("/home/sergio/simulador/Simulador_Cuantica/quantum-sim/main/circuit_random.qasm", "r") as f:
    qasm_str = f.read()
circ2 = loads(qasm_str)    

circ2.save_matrix_product_state(label='my_mps')
tcirc = transpile(circ2, simulator)
result = simulator.run(tcirc).result()
data = result.data(0)

#statevector = data['my_sv']
#print('statevector')
#print(statevector)

# Obtener el número de coeficientes del statevector
#num_coefficients_sv = len(statevector)
#num_coefficients_sv_list.append(num_coefficients_sv)

# Obtener el número de coeficientes del MPS
mps = data['my_mps']
print('mps')
print(mps[0])

mps
[(array([[ 0.93621622+0.j, -0.35142452+0.j]]), array([[-0.19849323+0.28999937j, -0.52879798+0.77257588j]])), (array([[ 0.24298724+0.5137935j ,  0.13383841-0.04129105j],
       [-0.26481388+0.28603613j,  0.34109765+0.49647656j]]), array([[ 1.04767269-0.07479299j, -0.34823006+0.09972829j],
       [ 0.06471495-0.40129523j,  0.76395074-1.18907969j]])), (array([[ 0.78414164-0.j],
       [-0.62058189-0.j]]), array([[0.19334322+0.58969508j],
       [0.24430051+0.74511434j]]))]


In [145]:
%config InlineBackend.figure_formats = ['svg']
import quimb as qu
import quimb.tensor as qtn
data2 =np.random.rand(2**5).reshape(2, 2, 2,2,2)  # Array de 5 sitios con 2 dimensiones por sitio
print(data2)

p = qtn.MPS_rand_state(L=5, bond_dim=2)
p = qtn.MatrixProductState.from_dense(data2)
print(f"Site tags: '{p.site_tag_id}', site inds: '{p.site_ind_id}'")
p.arrays

[[[[[0.13201859 0.53896571]
    [0.29932447 0.64111021]]

   [[0.45218806 0.71459313]
    [0.76563819 0.98392236]]]


  [[[0.8183294  0.79634663]
    [0.7613063  0.76000927]]

   [[0.46699699 0.22846245]
    [0.06170891 0.54884298]]]]



 [[[[0.55872687 0.78484652]
    [0.35131164 0.58358566]]

   [[0.58962223 0.31113827]
    [0.69968344 0.40047589]]]


  [[[0.2185619  0.35065637]
    [0.26304104 0.79702998]]

   [[0.76261613 0.06813428]
    [0.38326273 0.83966252]]]]]
Site tags: 'I{}', site inds: 'k{}'


(array([[-0.75632069, -0.65420106],
        [-0.65420106,  0.75632069]]),
 array([[[-0.72108306,  0.41519913,  0.54705583, -0.09153592],
         [-0.69226149, -0.42519141, -0.56705423,  0.13577847]],
 
        [[ 0.02584953,  0.49182325, -0.19737643,  0.8476345 ],
         [ 0.01204379, -0.63634255,  0.58328549,  0.50467925]]]),
 array([[[-0.69861885, -0.41494238,  0.13546595,  0.2671105 ],
         [-0.67127756,  0.45041173,  0.03690184, -0.195863  ]],
 
        [[-0.17333385,  0.19996429, -0.61825752,  0.28308137],
         [ 0.17623254,  0.23450722,  0.05861492,  0.60314742]],
 
        [[ 0.00943246,  0.19364341,  0.38008417, -0.43372937],
         [ 0.00206489,  0.58153115,  0.45655916,  0.29692898]],
 
        [[ 0.00836178, -0.00884696,  0.10381219,  0.35171946],
         [ 0.00724242,  0.39270628, -0.48054338, -0.21534442]]]),
 array([[[-0.63738228,  0.25906633],
         [-0.75589981, -0.17841436]],
 
        [[-0.04238242, -0.70714239],
         [ 0.01313868,  0.07086278]],
