In [1]:
import torch
import tensorkrowch as tk

net = tk.TensorNetwork()

node1 = tk.randn(shape=(7, 5),
                 axes_names=('left', 'right'),
                 name='node1',
                 network=net,
                 param_node=True)
node2 = tk.randn(shape=(7, 5),
                 axes_names=('left', 'right'),
                 name='node2',
                 network=net,
                 param_node=True)

node1['left'] ^ node2['left']
node1['right'] ^ node2['right']

Edge( node1[right] <-> node2[right] )

La manera de inicializar un nodo es la siguiente:

In [40]:
tensor = torch.randn(2, 5, 2)
node = tk.Node(tensor = tensor, name = 'Nodo(0)', axes_names = ['up', 'down','left'])
print(node.shape)
print(node.name)
print(node.axes_names)

torch.Size([2, 5, 2])
Nodo(0)
['up', 'down', 'left']


In [37]:
node.get_axis('up').name = 'batch'  # Changes the axis' name
idx = node.get_axis_num('batch')      # Devuelve el índice del nuevo edge
print(idx) 


0


Como crear una Tensor Network. <br>
La idea es conectar los índices entre los nodos.

In [ ]:
node['other_left']

Nodo(0)[other_left] <-> None


In [44]:
node['up'].is_dangling()  # Indicates if the edge is not connected
print(node['up'].is_dangling())
node['down'].is_batch()     # Indicates if the edge is a batch edge
print(node['down'].is_batch())
node['left'].size()         # Returns the shape of the node in that axis


True
False


2

In [76]:
net = tk.TensorNetwork()

node1 = tk.randn(shape=(2, 5, 2),
                 axes_names=('left', 'input', 'right'),
                 name='node1',
                 network=net)
node2 = tk.randn(shape=(2, 5, 2),
                 axes_names=('left', 'input', 'right'),
                 name='node2',
                 network=net)

assert net['node1'] is node1

In [62]:
print(net.nodes)

{'node1': Node(
 	name: node1
	tensor:
		tensor([[[ 0.0144,  0.0522],
		         [-0.6245,  0.3650],
		         [-0.2078, -1.0250],
		         [-1.3048,  0.0542],
		         [ 1.2640, -0.6706]],
		
		        [[ 0.1939, -2.7143],
		         [-1.4612,  0.4894],
		         [-1.2224, -0.8649],
		         [ 0.5690, -0.5865],
		         [-1.7156,  0.1706]]])
	axes:
		[left
		 input
		 right]
	edges:
		[node1[left] <-> None
		 node1[input] <-> None
		 node1[right] <-> None]), 'node2': Node(
 	name: node2
	tensor:
		tensor([[[-1.0640, -1.1630],
		         [ 0.0913, -0.4974],
		         [-2.0165,  0.6627],
		         [-0.5640, -0.0977],
		         [-1.7670, -0.9756]],
		
		        [[ 2.1230,  2.5648],
		         [ 1.4863, -1.1141],
		         [ 0.5316, -0.5715],
		         [ 1.5027,  1.0017],
		         [-0.2192, -0.4888]]])
	axes:
		[left
		 input
		 right]
	edges:
		[node2[left] <-> None
		 node2[input] <-> None
		 node2[right] <-> None])}


La forma de concetar los nodos y formar un grafo es la siguiente:


In [63]:
node1['right'] ^ node2['left']

Edge( node1[right] <-> node2[left] )

También se pueden desconectar los indices entre nodos de la red

In [64]:
node1['right'].disconnect()
# o equivalementemente:
#node1['right'] | node2['left']

(Edge( node1[right] <-> None )  (Dangling Edge),
 Edge( node2[left] <-> None )  (Dangling Edge))

In [72]:
print(net.nodes)

{'node1': Node(
 	name: node1
	tensor:
		tensor([[[ 0.0710,  1.5121],
		         [ 0.4031,  1.8117],
		         [-0.8171,  0.0182],
		         [-0.7247, -0.4807],
		         [ 0.0224, -1.1804]],
		
		        [[-0.6178, -1.6435],
		         [ 1.1140,  0.0356],
		         [-0.2043,  1.4699],
		         [ 2.1978, -0.1960],
		         [ 0.2491, -1.1544]]])
	axes:
		[left
		 input
		 right]
	edges:
		[node1[left] <-> None
		 node1[input] <-> None
		 node1[right] <-> None]), 'node2': Node(
 	name: node2
	tensor:
		tensor([[[-0.4732, -1.1695],
		         [-0.5423, -0.4573],
		         [ 0.2777, -1.5348],
		         [-0.4735, -0.6570],
		         [-0.2003,  0.2000]],
		
		        [[ 1.5897, -0.3611],
		         [ 1.7032, -0.3615],
		         [-0.5912,  0.1822],
		         [-0.3847,  1.4065],
		         [ 0.1471, -0.4294]]])
	axes:
		[left
		 input
		 right]
	edges:
		[node2[left] <-> None
		 node2[input] <-> None
		 node2[right] <-> None])}


Veamos como contraer una tensor network

In [120]:
net = tk.TensorNetwork()

node1 = tk.randn(shape=(2, 5, 2),
                 axes_names=('left', 'input', 'right'),
                 name='node1',
                 network=net)
node2 = tk.randn(shape=(2, 5, 2),
                 axes_names=('left', 'input', 'right'),
                 name='node2',
                 network=net)

assert net['node1'] is node1

node1['left'] ^ node2['left']
node1['right'] ^ node2['right']
#node1['input'] ^ node2['input']

#print(net.nodes)
print("despues de la contracción")
result = node1@node2
print(net.nodes_names)
#v=tk.contract_between_(node1,node2)
#cambiar el nombre de un nodo
node1.name='hola'
print(type(net))


despues de la contracción
['node1', 'node2', 'contract_edges']
<class 'tensorkrowch.components.TensorNetwork'>
